server:
  undertow:
    threads:
      worker: 10
      io: 2

mysql:
  username: root
  password: admin
  schema: adm_videos
  url: localhost:3306

amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: admin
  password: admin

keycloak:
  realm: fc3-codeflix
  host: http://localhost:8443