spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

logging:
  level:
    ROOT: info

mysql:
  username: root
  password: admin
  schema: adm_videos
  url: localhost:${mysql.port}

amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: admin
  password: admin

keycloak:
  realm: test
  host: http://test:8443