spring:
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: none

mysql:
  username: ${DATABASE_MYSQL_USERNAME}
  password: ${DATABASE_MYSQL_PASSWORD}
  schema: ${DATABASE_SCHEMA}
  url: ${DATABASE_URL}

amqp:
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}

keycloak:
  realm: ${KEYCLOAK_REALM:fc3-codeflix}
  host: ${KEYCLOAK_HOST:http://localhost:8443}