spring:
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: none

mysql:
  username: ${DATABASE_MYSQL_USERNAME}
  password: ${DATABASE_MYSQL_PASSWORD}
  schema: ${DATABASE_SCHEMA}
  url: ${DATABASE_URL}