server:
  port: 1000
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/json
    min-response-type: 1025
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  profiles:
    active: development
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      poo-name: master
    jpa:
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        "[hibernate.dialect]": org.hibernate.dialect.MySQL5InnoDBDialect
        "[hibernate.generate_statistics]": true
        "[hibernate.connection.provider_disables_autocommit]": true

google:
  cloud:
    credentials: ${GOOGLE_CLOUD_CREDENTIALS}
    project-id: ${GOOGLE_CLOUD_PROJECT_ID}
    storage:
      catalog-video:
        bucket: fc3_catalog_videos_ip
        connect-timeout: 1000
        read-timeout: 2000
        retry-delay: 50
        retry-max-delay: 50
        retry-max-attempts: 50
        retry-multiplier: 1.0

storage:
  catalog-video:
    location-pattern: videoId-{videoId}
    filename-pattern: type-{type}
