spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

logging:
  level:
    ROOT: info

mysql:
  username: root
  password: admin
  schema: adm_videos
  url: localhost:${mysql.port}