server:
  port: 1010

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:adm_videos_test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2
