version: '3.7'

services:
  app:
    container_name: adm_videos_app
    build: .
    profiles: ['app']
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - local

  mysql:
    container_name: adm_videos_mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: adm_videos
      MYSQL_ROOT_PASSWORD: admin
    security_opt:
      - seccomp:unconfined
    ports:
      - '3306:3306'
    networks:
      - local

  rabbitmq:
    container_name: adm_videos_rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: Q8w@f7!vD2k#Z3rXpT9e&BnL^mGhY0sW
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - local

networks:
  local:
