name: CI Pipeline

on:
  workflow_call:

jobs:
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run application tests
        run: mvn test
